version: '3.9'

services:
  golfr-api:
    build:
      context: .
      target: deps
    ports: 
      - "3030:3030"
    depends_on:
      - golfr-api-db
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./ormconfig.js:/app/ormconfig.js
      - ./app/node_modules
    env_file: ./application.env
    entrypoint: yarn
    command: run start:dev
  golfr-api-db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes: 
      - golfr-api-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: golfr
      POSTGRES_PASSWORD: golfr
      POSTGRES_DB: golfr
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: golfr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: abcd
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - golfr-api-db

volumes:
    golfr-api-db:
    pgadmin-data:
