name: Docker Lint & Test CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "+++ :docker: Building image..."
      run: docker build -t golfr-api:$(date +%s) .
    - name: "+++ :eslint: Runnning linter..."
      run: make test
    - name: "+++ :jest: Runnning tests..."
      run: make lint
