name: Docker Lint & Test CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --t golfr-api:$(date +%s)
    - name: Tests
      run: make test
    - name: Lint
      run: make lint